### ISSUE TITLE
Packaging local html file is not working 

### ISSUE THREAD

**Issue by iarvindverma** [RickStrahl/Westwind.HtmlPackager#3]
Hi Rick,

Thanks for creating this great tool.

I've tried this for online packaging and it worked when you create self contained file but getting this error while creating a dependency folder package.
![image](https://user-images.githubusercontent.com/44722985/61946182-86ff3f80-afbf-11e9-898f-a5797057dcd8.png)

When you create package from local file it throw error  and self contained package doesn't have inline image as base64 and during the local resource process it down't copy the resources. 
 
![image](https://user-images.githubusercontent.com/44722985/61945975-004a6280-afbf-11e9-9892-bd631b05b55c.png)

**Comment by RickStrahl** [comment]
That looks like file permissions on your host system. Perhaps try running this out of your user folder where you have full permissions.

**Comment by iarvindverma** [comment]
Running the app with admin permission, still getting the error

**Comment by RickStrahl** [comment]
File Permissions or a path longer than MAX_PATH would be my guess. Or perhaps an invalid file/folder name.
